site_name: Blocket-API.se
repo_url: https://github.com/dunderrrrrr/blocket_api

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - toc.integrate
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  icon:
    logo: material/car-lifted-pickup

extra_css:
  - custom.css

nav:
  - Main: index.md
  - preparations.md
  - API reference: api-reference.md
  - examples.md
  - Swaggerâ¤´: https://blocket-api.se/swagger

plugins:
   - search
   - swagger-ui-tag:
        syntaxHighlightTheme: monokai
        extra_css: ["api.css"]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dunderrrrrr/blocket_api

markdown_extensions:
  - pymdownx.superfences
  - admonition  
  - toc:
      permalink: true
