[tool.poetry]
authors = ["dunderrrrrr <emil.bjorkroth@gmail.com>"]
description = ""
name = "blocket_api"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
httpx = "^0.27.0"
python = "^3.12"
pre-commit = "^3.7.1"
ruff = "^0.5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
